apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.payara.fish
spec:
  group: payara.fish
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Namespaced
  versions:
    - name : v1beta
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                payara-image:
                  type: string
                application:
                  type: string
                instances:
                  type: integer
                config-script:
                  type: string
                artifact:
                  type: string
