apiVersion: payara.fish/v1beta
kind: Domain
metadata:
  name: example
spec:
  payara-image: payara/server-full:5.2021.1
  application: test
  # application will be used for deployment, service and deployment group name
  instances: 2
  config-script: test.boot
  artifact: test.war